name: example
description: "Kalua Example App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter

  follow_the_leader: ^0.5.2
  inception:
    path: /Users/admin/Projects/inception
  kalua:
    path: ../
  overlord: ^0.4.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  fonts:
    - family: SourceCodePro
      fonts:
        - asset: assets/fonts/Source_Code_Pro/static/SourceCodePro-Regular.ttf
        - asset: assets/fonts/Source_Code_Pro/static/SourceCodePro-Italic.ttf
          style: italic
        - asset: assets/fonts/Source_Code_Pro/static/SourceCodePro-Bold.ttf
          weight: 700
        - asset: assets/fonts/Source_Code_Pro/static/SourceCodePro-BoldItalic.ttf
          weight: 700
          style: italic
#        - asset: assets/fonts/Source_Code_Pro/SourceCodePro-VariableFont_wght.ttf
#        - asset: assets/fonts/Source_Code_Pro/SourceCodePro-Italic-VariableFont_wght.ttf
#          style: italic
